In [1]:
#Collatz suppose
import random
num = random.randint(1, 10 ** 10)
print(num)
while num != 1:
    if num % 2 == 0:
        num //= 2
    else:
        num = num * 3 + 1
    print("\t",num)

9552007445
	 28656022336
	 14328011168
	 7164005584
	 3582002792
	 1791001396
	 895500698
	 447750349
	 1343251048
	 671625524
	 335812762
	 167906381
	 503719144
	 251859572
	 125929786
	 62964893
	 188894680
	 94447340
	 47223670
	 23611835
	 70835506
	 35417753
	 106253260
	 53126630
	 26563315
	 79689946
	 39844973
	 119534920
	 59767460
	 29883730
	 14941865
	 44825596
	 22412798
	 11206399
	 33619198
	 16809599
	 50428798
	 25214399
	 75643198
	 37821599
	 113464798
	 56732399
	 170197198
	 85098599
	 255295798
	 127647899
	 382943698
	 191471849
	 574415548
	 287207774
	 143603887
	 430811662
	 215405831
	 646217494
	 323108747
	 969326242
	 484663121
	 1453989364
	 726994682
	 363497341
	 1090492024
	 545246012
	 272623006
	 136311503
	 408934510
	 204467255
	 613401766
	 306700883
	 920102650
	 460051325
	 1380153976
	 690076988
	 345038494
	 172519247
	 517557742
	 258778871
	 776336614
	 388168307
	 1164504922
	 582252461
	 1746757384
	 873378692
	 436689346
	 218344673
	 655034020
	 327517010
	 163758505
	 491275516
	 245637758
	 122818879
	 368456638
	 184228319
	 552684958
	 276342479
	 829027438
	 414513719
	 1243541158
	 621770579
	 1865311738
	 932655869
	 2797967608
	 1398983804
	 699491902
	 349745951
	 1049237854
	 524618927
	 1573856782
	 786928391
	 2360785174
	 1180392587
	 3541177762
	 1770588881
	 5311766644
	 2655883322
	 1327941661
	 3983824984
	 1991912492
	 995956246
	 497978123
	 1493934370
	 746967185
	 2240901556
	 1120450778
	 560225389
	 1680676168
	 840338084
	 420169042
	 210084521
	 630253564
	 315126782
	 157563391
	 472690174
	 236345087
	 709035262
	 354517631
	 1063552894
	 531776447
	 1595329342
	 797664671
	 2392994014
	 1196497007
	 3589491022
	 1794745511
	 5384236534
	 2692118267
	 8076354802
	 4038177401
	 12114532204
	 6057266102
	 3028633051
	 9085899154
	 4542949577
	 13628848732
	 6814424366
	 3407212183
	 10221636550
	 5110818275
	 15332454826
	 7666227413
	 22998682240
	 11499341120
	 5749670560
	 2874835280
	 1437417640
	 718708820
	 359354410
	 179677205
	 539031616
	 269515808
	 134757904
	 67378952
	 33689476
	 16844738
	 8422369
	 25267108
	 12633554
	 6316777
	 18950332
	 9475166
	 4737583
	 14212750
	 7106375
	 21319126
	 10659563
	 31978690
	 15989345
	 47968036
	 23984018
	 11992009
	 35976028
	 17988014
	 8994007
	 26982022
	 13491011
	 40473034
	 20236517
	 60709552
	 30354776
	 15177388
	 7588694
	 3794347
	 11383042
	 5691521
	 17074564
	 8537282
	 4268641
	 12805924
	 6402962
	 3201481
	 9604444
	 4802222
	 2401111
	 7203334
	 3601667
	 10805002
	 5402501
	 16207504
	 8103752
	 4051876
	 2025938
	 1012969
	 3038908
	 1519454
	 759727
	 2279182
	 1139591
	 3418774
	 1709387
	 5128162
	 2564081
	 7692244
	 3846122
	 1923061
	 5769184
	 2884592
	 1442296
	 721148
	 360574
	 180287
	 540862
	 270431
	 811294
	 405647
	 1216942
	 608471
	 1825414
	 912707
	 2738122
	 1369061
	 4107184
	 2053592
	 1026796
	 513398
	 256699
	 770098
	 385049
	 1155148
	 577574
	 288787
	 866362
	 433181
	 1299544
	 649772
	 324886
	 162443
	 487330
	 243665
	 730996
	 365498
	 182749
	 548248
	 274124
	 137062
	 68531
	 205594
	 102797
	 308392
	 154196
	 77098
	 38549
	 115648
	 57824
	 28912
	 14456
	 7228
	 3614
	 1807
	 5422
	 2711
	 8134
	 4067
	 12202
	 6101
	 18304
	 9152
	 4576
	 2288
	 1144
	 572
	 286
	 143
	 430
	 215
	 646
	 323
	 970
	 485
	 1456
	 728
	 364
	 182
	 91
	 274
	 137
	 412
	 206
	 103
	 310
	 155
	 466
	 233
	 700
	 350
	 175
	 526
	 263
	 790
	 395
	 1186
	 593
	 1780
	 890
	 445
	 1336
	 668
	 334
	 167
	 502
	 251
	 754
	 377
	 1132
	 566
	 283
	 850
	 425
	 1276
	 638
	 319
	 958
	 479
	 1438
	 719
	 2158
	 1079
	 3238
	 1619
	 4858
	 2429
	 7288
	 3644
	 1822
	 911
	 2734
	 1367
	 4102
	 2051
	 6154
	 3077
	 9232
	 4616
	 2308
	 1154
	 577
	 1732
	 866
	 433
	 1300
	 650
	 325
	 976
	 488
	 244
	 122
	 61
	 184
	 92
	 46
	 23
	 70
	 35
	 106
	 53
	 160
	 80
	 40
	 20
	 10
	 5
	 16
	 8
	 4
	 2
	 1

In [7]:
for idx in range(3, 16):
    print(idx, end = ': ')
    value = idx
    while value != 1:
        value = value * 3 + 1 if value % 2 else value // 2
        print(value, end = ' ')
    else:
        print()

3: 10 5 16 8 4 2 1
4: 2 1
5: 16 8 4 2 1
6: 3 10 5 16 8 4 2 1
7: 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
8: 4 2 1
9: 28 14 7 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
10: 5 16 8 4 2 1
11: 34 17 52 26 13 40 20 10 5 16 8 4 2 1
12: 6 3 10 5 16 8 4 2 1
13: 40 20 10 5 16 8 4 2 1
14: 7 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1
15: 46 23 70 35 106 53 160 80 40 20 10 5 16 8 4 2 1